name: Consumer CI-Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  docker-ci:
    uses: mahekshahbad/docker-ci-pipeline-template/.github/workflows/docker-ci-template.yml@main

    with:
      image_name: mahekshahbad/consumer-image
      image_tag: 1.0.0
      jar_path: target/app.jar
      build_command: ./mvnw clean package

      sonar_project_key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
      sonar_token: ${{ vars.SONAR_TOKEN }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
