name: Consumer CI Pipeline

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: mahekshahbad/docker-ci-pipeline-template/.github/workflows/docker-ci-template.yml@main
    with:
      image_name: consumer-app
      image_tag: pr-${{ github.event.number }}
      jar_path: target/app.jar
      build_command: ./mvnw clean package

      sonar_project_key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
      sonar_token: ${{ vars.SONAR_TOKEN }}

      snyk_token: ${{ vars.SNYK_TOKEN }}

      jfrog_url: ${{ vars.JFROG_URL }}
      jfrog_docker_repo: ${{ vars.JFROG_DOCKER_REPO }}

      JFROG_USERNAME: ${{ vars.JFROG_USERNAME }}
      JFROG_API_KEY: ${{ vars.JFROG_API_KEY }}
